twittermodoki/config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index' # 追加する
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

twittermodoki/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

twittermodoki/app/models/post.rb
class Post < ApplicationRecord
        validates :content, presence: true
        validates :content, length: { in: 1..140 }
end

twittermodoki/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

twittermodoki/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
  
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: "ツイートができました" }
        format.json { render :show, status: :created, location: @post }
      else
        @posts = Post.all
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "更新されました。" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "ツイートを消しました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content)
    end
end

twittermodoki/app/helpers/application_helper.rb
module ApplicationHelper
end

twittermodoki/app/helpers/posts_helper.rb
module PostsHelper
end

twittermodoki/app/helpers/twitters_helper.rb
module TwittersHelper
end

twittermodoki/app/views/layouts/_footer.html.erb
<footer class="footer">
<nav>
    <ul class="footer_nav">
        <a class="footer_nav_item">
            <li>Home</li>
        </a>
        <a class="footer_nav_item">
            <li>about</li>
        </a>
        <a class="footer_nav_item">
            <li>Contact</li>
        </a>
    </ul>
</nav>
</footer>

twittermodoki/app/views/layouts/_header.html.erb
<header>
<nav class="header_nav">
    <div class = "global_nav_item">twittermodoki</div>
    <ul class="global_nav">
        <a class = "global_nav_item">
        <li>Home</li>
        </a>
        <a class = "global_nav_item">
        <li>about</li>
        </a>
        <a class = "global_nav_item">
        <li>Contact</li>
        </a>
</nav>
</header>

twittermodoki/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittermodoki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
    <%= yield %>
    <main>
    <%= render 'layouts/footer' %>
  </body>
</html>

twittermodoki/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> ポストに投稿できない内容がありました:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :ツイート内容 %>
  <%= form.text_area :content, class: 'text-area-large' %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

twittermodoki/app/views/posts/edit.html.erb
<br>
<br>
<h1>ツイートを編集します</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

twittermodoki/app/views/posts/index.html.erb
<br>
<br>

<p id="notice"><%= notice %></p>

<br>
<br>

<div>
  <%= render 'form', post: @post %>
</div>

<div class="section_title">
  <h1>タイムライン</h1>
</div>

<table>
  <tbody>
    <% @posts.reverse.each do |post| %>
      <tr>
        <td colspan="3">
          <%= content_tag :div, post.content, class: 'TEXT_FORMAT1' %>
        </td>
      </tr>
      <tr>
        <td><%= link_to '詳細', post %></td>
        <td><%= link_to '編集', edit_post_path(post) %></td>
        <td><%= link_to '削除', post, method: :delete, data: { confirm: '削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

twittermodoki/app/views/posts/new.html.erb
<br>
<br>
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

twittermodoki/app/views/posts/show.html.erb
<br>
<br>

<p id="notice"><%= notice %></p>

<p>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>